[Application]
# Whether to log general debugging information or not.
APP_DEBUG = "off"

# The bot Hirsh will use to perform all of its duties.
BOT_TOKEN = ""

[Moderation]
# You can choose to enable (on) or disable (off) this feature depending on
# whether you wish for Hirsh to keep moderation logs.
LOGS_STATUS = "on"

# If moderation logs are enabled, this will serve as the channel(s)
# in which Hirsh keeps all of its logs. Enter channel ID(s) here.
LOGS_CHANNELS = [""]

[Ignores]
# If you have any roles you'd like Hirsh to ignore when users leave/rejoin, add their IDs here.
IGNORED_ROLES = [""]

# If you plan on running Hirsh under a bot that serves multiple servers, you can choose
# to have it so that Hirsh doesn't execute in certain servers. Enter ID(s) here.
IGNORED_GUILDS = [""]
